
# Formatted tables

## Table 1: Overall method performance

```{r table1-overall, eval=FALSE}
table1 <- method_summary %>%
  transmute(
    N = n,
    rho = rho,
    Method = method,
    `Avg TP` = round(mean_TP, 3),
    `Avg FP` = round(mean_FP, 3),
    `Avg Model Size` = round(mean_model_size, 3),
    `TPR` = round(mean_TPR, 4),
    `MCSE TPR` = round(mcse_TPR, 4),
    `FPR` = round(mean_FPR, 4),
    `MCSE FPR` = round(mcse_FPR, 4)
  ) %>%
  arrange(N, rho, Method)

table1 %>%
  kable(
    caption = "Table 1. Overall Selection Performance by Sample Size and Predictor Correlation",
    align = "c",
    booktabs = TRUE
  ) %>%
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 10,
    bootstrap_options = c("striped", "hover", "condensed")
  ) %>%
  collapse_rows(columns = 1:2, valign = "top")
```

## Table 2: True-variable performance

```{r table2-true-vars, eval=FALSE}
table2 <- variable_summary %>%
  filter(beta_true != 0) %>%
  transmute(
    N = n,
    rho = rho,
    Method = method,
    Variable = variable,
    `True Beta` = round(beta_true, 4),
    `Selection Probability` = round(selection_probability, 4),
    `MCSE Selection` = round(mcse_selection_probability, 4),
    `Mean Bias` = round(mean_bias_uncond, 4),
    `MCSE Bias` = round(mcse_bias_uncond, 4),
    `Coverage` = round(coverage_probability, 4),
    `MCSE Coverage` = round(mcse_coverage, 4),
    `Type II Error` = round(type2_error_rate, 4)
  ) %>%
  arrange(N, rho, Method, Variable)

table2 %>%
  kable(
    caption = "Table 2. Variable-Level Performance for Truly Associated Predictors",
    align = "c",
    booktabs = TRUE
  ) %>%
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 9,
    bootstrap_options = c("striped", "hover", "condensed")
  ) %>%
  collapse_rows(columns = 1:3, valign = "top")
```

## Table 3: Null-variable performance

```{r table3-null-vars, eval=FALSE}
table3 <- variable_summary %>%
  filter(beta_true == 0) %>%
  transmute(
    N = n,
    rho = rho,
    Method = method,
    Variable = variable,
    `False Positive Rate` = round(selection_probability, 4),
    `MCSE FPR` = round(mcse_selection_probability, 4),
    `Type I Error` = round(type1_error_rate, 4)
  ) %>%
  arrange(N, rho, Method, Variable)

table3 %>%
  kable(
    caption = "Table 3. Variable-Level False Positive Rates and Type I Error for Null Predictors",
    align = "c",
    booktabs = TRUE
  ) %>%
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8,
    bootstrap_options = c("striped", "hover", "condensed")
  ) %>%
  collapse_rows(columns = 1:3, valign = "top")
```



# Save final summary tables

```{r save-final-tables, eval=FALSE}
write.csv(table1, file.path(results_tbl, "Table1_Overall_Performance.csv"), row.names = FALSE)
write.csv(table2, file.path(results_tbl, "Table2_True_Variable_Performance.csv"), row.names = FALSE)
write.csv(table3, file.path(results_tbl, "Table3_Null_Variable_Performance.csv"), row.names = FALSE)
```


